# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
zh-hant:
 languageCode: zh-hant
 contentDir: content/zh
 title: 即時控制實驗室
 params:
   description: 分析非線性系統的實驗室
 menu:
   main:
    - name: 導覽
      url: tour
      weight: 10
    - name: 文章
      url: post
      weight: 20
    - name: 成員
      url: people
      weight: 30
    - name: 活動
      url: event
      weight: 40
    - name: 發表
      url: publication
      weight: 50
    - name: 聯絡我們
      url: contact
      weight: 60

